### ISSUE TITLE
Pseudononymize current value with a custom provider

### ISSUE THREAD

**Issue by dosera** [rwnx/pynonymizer#130]
I have a table/column that I want to pseudonymize where it is not sufficient to work with the `LITERAL` type (my database does not support what I want to do).
I created a custom provider as follows:

```
from faker.providers import BaseProvider

class MyProvider(BaseProvider):
    def mypseudo(self):
        return originalValue.replace("a", "b")
```

which I can use in my strategy file just fine:

```
providers:
  - providers.myprovider.MyProvider

tables:
  TABLE:
    columns:
      COLUMN:
        type: mypseudo
```

**Describe the solution you'd like**
I want to have a way to give the `current column value` to my `mypseudo` to perform "things" on it.

**Describe alternatives you've considered**
I tried using `fake_args` as written in the docs - but didn't manage to get the current value "injected" into my method.
E.g. something like

```
...
      COLUMN:
        type: mypseudo
        fake_args:
          current: (SELECT COLUMN)
```

Did not work.

Am I missing something or is this feature not available yet?
