### ISSUE TITLE
Doubts pynonymizer

### ISSUE THREAD

**Issue by thandrade830** [rwnx/pynonymizer#176]
Good afternoon everyone,
I have the following questions:

- How can i leave the columns as NULL?
- For example i have two tables that have a person's name:
Table A - Thiago Andrade
Table B - Thiago Andrade
How do I get the same faker name to be generated?
Generating in the standard way creates a different name for each table.

I appreciate anyone who can help me.

**Comment by rwnx** [comment]
Hi, there's no way to do it directly, but you might be able to do it with a custom script: see the [scripts](https://github.com/rwnx/pynonymizer/blob/main/doc/strategyfiles.md#key-scripts) feature.

**Comment by lryb** [comment]
`literal` columns are not really literal, but sql that is inserted into the update query.
You can add something like this to your strategyfile to get the username from the same table or from other tables (assuming both tables have an id linking them)

```
  users_a:
    columns:
      login:
        type: fake_update
        fake_type: user_name
      email: ( CONCAT(login, "@example.com"))
  users_b:
    columns:
      - column_name: username
        type: literal
        value: (SELECT login from users_a where id=user_id)
```

It's not super efficient, since the query is ran for every user, but if your database is not enormous it should be fast enough. Also make sure to have `users_a` above `users_b`, so its sql is ran first.
