### ISSUE TITLE
Not able to support randomizing a jsonb type

### ISSUE THREAD

**Issue by stoiven** [rwnx/pynonymizer#91]
**Describe the bug**
Trying to randomize a specific portion in a json field, but there is no specific expression to declare it as. 

**To Reproduce**
In the `.yaml` file, have this:
```
  table:
    columns:
      params: 
        type: literal
        value: CASE WHEN params->>'email' ~ LOWER('website.com[[:>:]]') THEN params->>'email' ELSE CONCAT(DIGEST(LOWER(params->>'email'), 'sha1'), '@websitefaker.com') END
```
The structure of the table is:
```
     Column      |            Type             |                           Modifiers
-----------------+-----------------------------+---------------------------------------------------------------
 blob_random     | integer                     | not null default nextval('table_name_id_seq'::regclass)
 random_id       | text                        | not null
 completion_time | timestamp without time zone | default now()
 params          | jsonb                       |
```
The `params` field is this whole blob of json fields e.g.:

```
{
  "blob": 173467,
  "blobby": 20274,
  "service": "random",
  "owners": [
    "chris@googlefake.com"
  ]
}
```

When trying to anonymize, I get `ERROR:  column "params" is of type jsonb but expression is of type text`

**Expected behavior**

The `value` output should change only the specified params (tested this on the local database itself, so it should work here)
Ran a `SELECT CASE WHEN params->>'email' ~ LOWER('website.com[[:>:]]') THEN params->>'email' ELSE CONCAT(DIGEST(LOWER(params->>'email'), 'sha1'), '@websitefaker.com') END FROM table_name`

So the output should be:

```
{
  "blob": 173467,
  "blobby": 20274,
  "service": "random",
  "owners": [
    "sdfkj@websitefaker.com"
  ]
}
```
