### ISSUE TITLE
anyway to escape : from yaml file

### ISSUE THREAD

**Issue by amz4u2nv** [rwnx/pynonymizer#99]
For example if strategy file is like

tables:
  user_session: truncate
scripts:
  after:
    - UPDATE test_lead SET details = ' "test": false, "brokerName": "dd"'
    

it errors with - 
yaml.scanner.ScannerError: while scanning a quoted scalar
  in "test.yaml", line 5, column 82
found unexpected end of stream
  in "test.yaml", line 5, column 83

If i remote the : then it works, is there a way to escape, and allow the sql update allow for : in column.

Thanks

**Comment by rwnx** [comment]
Hi, 
I think the problem is that it's not valid yaml. if you want to include double quotes in a yaml string you need to encapsulate the whole string (and escape the double quotes). 

I would recommend that you check out yaml handles strings to get a better understanding of the different ways you could solve this:

e.g.

```yaml
tables:
  user_session: truncate
scripts:
  after:
    - "UPDATE test_lead SET details = ' \"test\": false, \"brokerName\": \"dd\"'"
```
